export const ADD_TO_FRIENDSLIST = 'ADD_TO_FRIENDSLIST';
export const ADD_TO_CHALLENGESLIST = 'ADD_TO_CHALLENGESLIST';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_KEY = 'SET_USER_KEY';
